# Generated by Django 4.0.3 on 2023-04-02 18:35

import django.core.validators
from django.db import migrations, models
import myPlantApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[myPlantApp.models.validate_start_capital_letter])),
                ('last_name', models.CharField(max_length=20, validators=[myPlantApp.models.validate_start_capital_letter])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
