# Generated by Django 4.0.3 on 2023-04-02 18:47

from django.db import migrations, models
import myPlantApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myPlantApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('Outdoor Plants', 'Outdoor Plants'), ('Indoor Plants', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=20, validators=[myPlantApp.models.validate_only_alphanumeric])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
