# Generated by Django 4.0.3 on 2023-04-02 21:04

import django.core.validators
from django.db import migrations, models
import myPlantApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myPlantApp', '0003_rename_model_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmodel',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='plantmodel',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), myPlantApp.models.validate_only_alphanumeric]),
        ),
        migrations.AlterField(
            model_name='plantmodel',
            name='plant_type',
            field=models.CharField(choices=[('Outdoor Plants', 'Outdoor Plants'), ('Indoor Plants', 'Indoor Plants')], max_length=14, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(max_length=20, validators=[myPlantApp.models.validate_start_capital_letter], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(max_length=20, validators=[myPlantApp.models.validate_start_capital_letter], verbose_name='Last Name'),
        ),
    ]
