# Generated by Django 4.2 on 2023-06-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_gamemodel_max_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamemodel",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="Summary"),
        ),
    ]
