# Generated by Django 4.2 on 2023-06-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecipesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Title")),
                ("image_url", models.URLField(verbose_name="Image URL")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "ingredients",
                    models.CharField(max_length=250, verbose_name="Ingredients"),
                ),
                ("time", models.IntegerField(verbose_name="Time (Minutes)")),
            ],
        ),
    ]
