# Generated by Django 4.2.2 on 2023-06-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BooksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Title")),
                ("description", models.CharField(verbose_name="Description")),
                ("image", models.ImageField(upload_to="", verbose_name="Image")),
                ("type", models.CharField(max_length=30, verbose_name="Type")),
            ],
        ),
    ]
