# Generated by Django 4.2.2 on 2023-06-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booksmodel",
            name="image",
            field=models.URLField(verbose_name="Image"),
        ),
    ]
