# Generated by Django 4.0.3 on 2023-04-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPlantApp', '0002_plantmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='ProfileModel',
        ),
    ]
