# Generated by Django 4.2 on 2023-06-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="image_url",
            field=models.URLField(verbose_name="Image URL"),
        ),
    ]
