# Generated by Django 4.0.3 on 2023-04-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='last_name',
            new_name='last_Name',
        ),
    ]
