# Generated by Django 4.2 on 2023-06-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Title")),
                ("image_url", models.URLField(verbose_name="Link to Image")),
                ("content", models.TextField(verbose_name="Content")),
            ],
        ),
    ]
