# Generated by Django 4.2 on 2023-06-24 06:16

import apps.functionality.custom_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=25,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            apps.functionality.custom_validators.CustomValidators.letter_start,
                        ],
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=35,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            apps.functionality.custom_validators.CustomValidators.letter_start,
                        ],
                        verbose_name="Last Name",
                    ),
                ),
                ("email", models.EmailField(max_length=40, verbose_name="Email")),
                (
                    "password",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(8)],
                        verbose_name="Email",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="Image URL"),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True, default=18, null=True, verbose_name="Age"
                    ),
                ),
            ],
        ),
    ]
