# Generated by Django 4.2 on 2023-06-24 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="password",
            field=models.CharField(
                max_length=20,
                validators=[django.core.validators.MinLengthValidator(8)],
                verbose_name="Password",
            ),
        ),
    ]
